services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: kraijai-client
    restart: always
    ports:
      - "4000:3000"
    networks:
      - nginx-proxy-net

networks:
  nginx-proxy-net:
    external: true