services:
  client:
    image: ghcr.io/pichaya-big/kraijai-client:${TAG:-latest}
    container_name: kraijai-client
    restart: always
    networks:
      - nginx-proxy-net
    expose:
      - 3000
    
networks:
  nginx-proxy-net:
    external: true